spring.application.name=incident-management

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://kavindugayantha111_db_user:U8nbofSi3KAvZ022@cluster0.4hqcjeu.mongodb.net/smartcampus_db

# Server Port
server.port=8080

# File Upload Setup
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

# Custom property for file storage path
file.upload-dir=uploads

# Allow cross origin requests (for dev)
spring.mvc.cors.mappings[/**].allowed-origins=*
spring.mvc.cors.mappings[/**].allowed-methods=*

# Admin user configuration
app.admin.email=admin@gmail.com
app.admin.name=Admin
app.admin.password=Admin@123

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=placeholder
spring.security.oauth2.client.registration.google.client-secret=placeholder
spring.security.oauth2.client.registration.google.scope=email,profile
